gui:
  theme:
    activeBorderColor:
      - "#6c94ff"
      - bold
    inactiveBorderColor:
      - "#a0a9cb"
    selectedLineBgColor:
      - "#212736"
    optionsTextColor:
      - "#769ff0"
    cherryPickedCommitFgColor:
      - "#6c94ff"
    cherryPickedCommitBgColor:
      - "#212736"
  nerdFontsVersion: "3"
  showRandomTip: false
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers
